"""Bounded 3D cognitive constraint propagation for Jarvis-X.

The engine maps symbolic facts onto a three-axis cognitive chart:

- x: perceptual structure,
- y: relational structure,
- z: abstraction depth.

The 3D coordinates are an explicit software representation, not a claim that
reasoning literally occurs in physical three-dimensional space.

Constraints are linear equalities propagated until a fixed point is reached.
Only fully resolved, numerically consistent states are accepted.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable, Mapping

Scalar = int | float
Point3D = tuple[float, float, float]


class CognitiveConstraintError(ValueError):
    """Raised when a cognitive-constraint input violates the runtime contract."""


def _finite(value: Scalar, *, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise CognitiveConstraintError(f"{name} must be numeric")
    result = float(value)
    if not math.isfinite(result):
        raise CognitiveConstraintError(f"{name} must be finite")
    return result


def _point3(value: Iterable[Scalar], *, name: str) -> Point3D:
    point = tuple(_finite(item, name=name) for item in value)
    if len(point) != 3:
        raise CognitiveConstraintError(f"{name} must contain exactly three values")
    return (point[0], point[1], point[2])


@dataclass(frozen=True, slots=True)
class CognitiveVariable3D:
    """One scalar reasoning variable placed on the software cognitive chart."""

    name: str
    coordinate: Point3D
    initial_value: float | None = None
    provenance: str = "unspecified"

    def __post_init__(self) -> None:
        if not self.name:
            raise CognitiveConstraintError("variable name must be non-empty")
        object.__setattr__(
            self,
            "coordinate",
            _point3(self.coordinate, name=f"{self.name}.coordinate"),
        )
        if self.initial_value is not None:
            object.__setattr__(
                self,
                "initial_value",
                _finite(self.initial_value, name=f"{self.name}.initial_value"),
            )


@dataclass(frozen=True, slots=True)
class LinearConstraint:
    """A linear equality: sum(coeff_i * value_i) == constant."""

    name: str
    terms: tuple[tuple[str, float], ...]
    constant: float
    semantic: str

    def __post_init__(self) -> None:
        if not self.name:
            raise CognitiveConstraintError("constraint name must be non-empty")
        if not self.terms:
            raise CognitiveConstraintError("constraint must contain at least one term")
        if not self.semantic:
            raise CognitiveConstraintError("constraint semantic must be non-empty")

        seen: set[str] = set()
        normalized: list[tuple[str, float]] = []
        for variable, coefficient in self.terms:
            if not variable:
                raise CognitiveConstraintError("constraint variable name must be non-empty")
            if variable in seen:
                raise CognitiveConstraintError(
                    f"constraint {self.name!r} repeats variable {variable!r}"
                )
            seen.add(variable)
            coeff = _finite(coefficient, name=f"{self.name}.{variable}.coefficient")
            if abs(coeff) == 0.0:
                raise CognitiveConstraintError(
                    f"constraint {self.name!r} has zero coefficient for {variable!r}"
                )
            normalized.append((variable, coeff))

        object.__setattr__(self, "terms", tuple(normalized))
        object.__setattr__(
            self,
            "constant",
            _finite(self.constant, name=f"{self.name}.constant"),
        )


@dataclass(frozen=True, slots=True)
class CognitiveInferenceStep:
    """One auditable inference generated by a single constraint."""

    iteration: int
    variable: str
    value: float
    coordinate: Point3D
    constraint: str
    semantic: str


@dataclass(frozen=True, slots=True)
class CognitiveFixedPointReceipt:
    """Evidence receipt for a bounded cognitive fixed point."""

    values: tuple[tuple[str, float], ...]
    trajectory: tuple[CognitiveInferenceStep, ...]
    residuals: tuple[tuple[str, float], ...]
    unresolved: tuple[str, ...]
    iterations: int
    fixed_point_reached: bool
    max_residual: float
    accepted: bool
    claim_status: str = "computational_constraint_process_only"

    def value(self, name: str) -> float:
        for key, value in self.values:
            if key == name:
                return value
        raise KeyError(name)


class CognitiveConstraintField3D:
    """Propagate declared constraints over a bounded 3D cognitive chart."""

    def __init__(
        self,
        variables: Iterable[CognitiveVariable3D],
        constraints: Iterable[LinearConstraint],
        *,
        tolerance: float = 1e-9,
        max_iterations: int = 64,
    ) -> None:
        tolerance_value = _finite(tolerance, name="tolerance")
        if tolerance_value < 0.0:
            raise CognitiveConstraintError("tolerance must be non-negative")
        if isinstance(max_iterations, bool) or not isinstance(max_iterations, int):
            raise CognitiveConstraintError("max_iterations must be an integer")
        if max_iterations <= 0:
            raise CognitiveConstraintError("max_iterations must be positive")

        variable_list = tuple(variables)
        constraint_list = tuple(constraints)
        if not variable_list:
            raise CognitiveConstraintError("at least one cognitive variable is required")
        if not constraint_list:
            raise CognitiveConstraintError("at least one constraint is required")

        names = [variable.name for variable in variable_list]
        if len(names) != len(set(names)):
            raise CognitiveConstraintError("cognitive variable names must be unique")

        self._variables = {variable.name: variable for variable in variable_list}
        self._constraints = constraint_list
        self.tolerance = tolerance_value
        self.max_iterations = max_iterations

        declared = set(self._variables)
        for constraint in self._constraints:
            for variable, _ in constraint.terms:
                if variable not in declared:
                    raise CognitiveConstraintError(
                        f"constraint {constraint.name!r} references unknown variable {variable!r}"
                    )

    @property
    def coordinates(self) -> Mapping[str, Point3D]:
        return {name: variable.coordinate for name, variable in self._variables.items()}

    def solve(self) -> CognitiveFixedPointReceipt:
        values = {
            name: variable.initial_value
            for name, variable in self._variables.items()
            if variable.initial_value is not None
        }
        trajectory: list[CognitiveInferenceStep] = []
        fixed_point_reached = False
        iterations = 0

        for iteration in range(1, self.max_iterations + 1):
            iterations = iteration
            changed = False

            for constraint in self._constraints:
                unknown = [
                    (name, coefficient)
                    for name, coefficient in constraint.terms
                    if name not in values
                ]
                if len(unknown) != 1:
                    continue

                target_name, target_coefficient = unknown[0]
                known_sum = sum(
                    coefficient * values[name]
                    for name, coefficient in constraint.terms
                    if name in values
                )
                inferred = (constraint.constant - known_sum) / target_coefficient
                inferred = _finite(
                    inferred,
                    name=f"{constraint.name}.{target_name}.inferred",
                )

                if target_name in values:
                    if abs(values[target_name] - inferred) > self.tolerance:
                        continue
                else:
                    values[target_name] = inferred
                    trajectory.append(
                        CognitiveInferenceStep(
                            iteration=iteration,
                            variable=target_name,
                            value=inferred,
                            coordinate=self._variables[target_name].coordinate,
                            constraint=constraint.name,
                            semantic=constraint.semantic,
                        )
                    )
                    changed = True

            if not changed:
                fixed_point_reached = True
                break

        residuals: list[tuple[str, float]] = []
        for constraint in self._constraints:
            if all(name in values for name, _ in constraint.terms):
                lhs = sum(coefficient * values[name] for name, coefficient in constraint.terms)
                residuals.append((constraint.name, abs(lhs - constraint.constant)))

        unresolved = tuple(name for name in self._variables if name not in values)
        max_residual = max((value for _, value in residuals), default=0.0)
        all_constraints_evaluable = len(residuals) == len(self._constraints)
        accepted = (
            fixed_point_reached
            and not unresolved
            and all_constraints_evaluable
            and max_residual <= self.tolerance
        )

        return CognitiveFixedPointReceipt(
            values=tuple(sorted((name, float(value)) for name, value in values.items())),
            trajectory=tuple(trajectory),
            residuals=tuple(residuals),
            unresolved=unresolved,
            iterations=iterations,
            fixed_point_reached=fixed_point_reached,
            max_residual=max_residual,
            accepted=accepted,
        )


def angle_demo_130_50() -> CognitiveFixedPointReceipt:
    """Run the motivating angle problem through the 3D cognitive process.

    The declared facts are:
    - top exterior angle = 130 degrees,
    - right interior angle = 50 degrees.

    Constraint propagation infers:
    - top interior = 50 degrees,
    - bottom interior = 80 degrees,
    - requested exterior angle d = 100 degrees.
    """

    variables = (
        CognitiveVariable3D(
            "top_exterior",
            (0.10, 0.10, 0.10),
            130.0,
            "visual observation",
        ),
        CognitiveVariable3D(
            "right_interior",
            (0.20, 0.20, 0.10),
            50.0,
            "visual observation",
        ),
        CognitiveVariable3D(
            "top_interior",
            (0.35, 0.40, 0.45),
            provenance="supplement inference",
        ),
        CognitiveVariable3D(
            "bottom_interior",
            (0.55, 0.65, 0.70),
            provenance="triangle invariant",
        ),
        CognitiveVariable3D(
            "d",
            (0.80, 0.85, 0.95),
            provenance="exterior-angle conclusion",
        ),
    )
    constraints = (
        LinearConstraint(
            "top_straight_line",
            (("top_exterior", 1.0), ("top_interior", 1.0)),
            180.0,
            "adjacent angles on a straight line sum to 180 degrees",
        ),
        LinearConstraint(
            "triangle_sum",
            (
                ("top_interior", 1.0),
                ("right_interior", 1.0),
                ("bottom_interior", 1.0),
            ),
            180.0,
            "interior angles of a Euclidean triangle sum to 180 degrees",
        ),
        LinearConstraint(
            "bottom_straight_line",
            (("bottom_interior", 1.0), ("d", 1.0)),
            180.0,
            "adjacent angles on a straight line sum to 180 degrees",
        ),
    )
    return CognitiveConstraintField3D(variables, constraints).solve()


__all__ = [
    "CognitiveConstraintError",
    "CognitiveConstraintField3D",
    "CognitiveFixedPointReceipt",
    "CognitiveInferenceStep",
    "CognitiveVariable3D",
    "LinearConstraint",
    "Point3D",
    "angle_demo_130_50",
]
