"""Self-contained browser control plane for the Dr Moagi 3D OS service."""

DR_MOAGI_OS_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<title>Dr Moagi 3D OS</title>
<style>
:root{color-scheme:dark;--bg:#04070b;--panel:#0b111a;--line:#233247;--text:#e9f2ff;--muted:#8fa0b5;--hot:#76d9ff;--gold:#ffd36d}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}
body{padding:14px}.shell{max-width:1440px;margin:0 auto}.top{display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap;align-items:flex-start}.title{font-weight:850;font-size:clamp(22px,4vw,38px);letter-spacing:-.04em}.sub{color:var(--muted);font-size:12px;line-height:1.5;max-width:760px;margin-top:6px}.status{display:grid;grid-template-columns:repeat(4,minmax(100px,1fr));gap:7px;min-width:min(100%,480px)}.m{border:1px solid var(--line);background:var(--panel);border-radius:11px;padding:9px}.m span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.m b{display:block;margin-top:3px;font-size:15px;overflow:hidden;text-overflow:ellipsis}.stage{display:flex;gap:6px;overflow:auto;padding:12px 0 9px}.stage i{font-style:normal;white-space:nowrap;border:1px solid var(--line);border-radius:999px;padding:6px 9px;color:var(--muted);font-size:9px;font-weight:750}.stage i.on{color:white;border-color:var(--hot);background:#0f2735}.grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,.45fr);gap:12px}.view,.panel{border:1px solid var(--line);border-radius:16px;background:var(--panel);overflow:hidden}.view{position:relative;background:radial-gradient(circle at 50% 45%,#102034 0,#07101a 48%,#020305 100%)}canvas{display:block;width:100%;height:auto;min-height:520px;aspect-ratio:16/10;touch-action:none}.overlay{position:absolute;left:10px;right:10px;bottom:10px;display:flex;gap:6px;flex-wrap:wrap;pointer-events:none}.chip{border:1px solid #2a3c52;background:#07101bd9;border-radius:999px;padding:6px 9px;font-size:9px;color:#9baabd}.panel{padding:12px}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px}button{min-height:43px;border-radius:10px;border:1px solid #34475f;background:#101a27;color:var(--text);font-weight:750;cursor:pointer}button.primary{background:#eef7ff;color:#071019;border-color:#eef7ff}button.danger{border-color:#69434a;color:#ffc6c6}.section{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);margin:14px 0 7px}.kv{display:grid;grid-template-columns:1fr auto;gap:7px;font-size:11px;padding:5px 0;border-bottom:1px solid #152131}.kv span{color:var(--muted)}.log{margin-top:10px;border:1px solid #1f2d40;border-radius:10px;background:#050a10;padding:8px;height:180px;overflow:auto;font:10px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;color:#9fb4ca}.footer{margin-top:10px;font-size:10px;color:var(--muted);line-height:1.5}@media(max-width:850px){body{padding:9px}.grid{grid-template-columns:1fr}.status{grid-template-columns:1fr 1fr}.view canvas{min-height:420px;aspect-ratio:4/5}}
</style>
</head>
<body><div class="shell">
<div class="top"><div><div class="title">Dr Moagi 3D OS</div><div class="sub">Sparse 3D state → binary voxel plane → Uint64 packing → inward fold/attenuation → auto-encode/decode → fixed-point projection → verified commit → closed-loop auto-execution.</div></div><div class="status"><div class="m"><span>Lifecycle</span><b id="life">—</b></div><div class="m"><span>Cycle</span><b id="cycle">0</b></div><div class="m"><span>Active cells</span><b id="active">0</b></div><div class="m"><span>Bit density</span><b id="density">0</b></div></div></div>
<div class="stage"><i>Voxelize</i><i>Pack64</i><i>Fold</i><i>Encode</i><i>Decode</i><i>Verify</i><i>Fixed Point</i><i>Commit</i><i>Permeate</i><i>Loop</i></div>
<div class="grid"><div class="view"><canvas id="c" width="1200" height="760"></canvas><div class="overlay"><span class="chip">drag: rotate</span><span class="chip">wheel: zoom</span><span class="chip">cyan: active voxel</span><span class="chip">gold: high magnitude</span></div></div>
<div class="panel"><div class="buttons"><button class="primary" id="demo">Boot Demo</button><button id="step">Single Step</button><button id="run">Run ×8</button><button id="auto">Auto Run</button><button id="stop">Stop</button><button class="danger" id="shutdown">Shutdown</button></div>
<div class="section">Runtime</div><div class="kv"><span>Phase velocity</span><b id="velocity">—</b></div><div class="kv"><span>Entropy</span><b id="entropy">—</b></div><div class="kv"><span>Kinetic energy</span><b id="energy">—</b></div><div class="kv"><span>Packed words</span><b id="words">—</b></div><div class="kv"><span>Reconstruction MSE</span><b id="mse">—</b></div><div class="kv"><span>Fixed-point residual</span><b id="fp">—</b></div><div class="kv"><span>Block / quant</span><b id="policy">—</b></div><div class="section">Execution journal</div><div class="log" id="log"></div><div class="footer">The browser is a control plane over a bounded sparse runtime. Logical volume is not dense resident memory; policy adaptation is constrained to validated runtime parameters.</div></div></div>
</div>
<script>
(()=>{const $=s=>document.querySelector(s),canvas=$('#c'),ctx=canvas.getContext('2d');let cells=[],yaw=-.55,pitch=.35,zoom=1,drag=false,lx=0,ly=0,stage=0;const log=(m)=>{const e=$('#log');e.textContent=`${new Date().toLocaleTimeString()}  ${m}\n`+e.textContent.slice(0,7000)};
async function req(path,opt){const r=await fetch(path,opt);let p;try{p=await r.json()}catch{p={detail:await r.text()}}if(!r.ok)throw new Error(p.detail||JSON.stringify(p));return p}
function setText(id,v){$(id).textContent=v===null||v===undefined?'—':String(v)}
async function refresh(){try{const s=await req('/v1/os/status');setText('#life',s.lifecycle);setText('#cycle',s.cycle);setText('#active',s.active_cells);setText('#density',Number(s.bitplane.density||0).toFixed(6));setText('#velocity',s.last_report?Number(s.last_report.phase_velocity).toFixed(6):'—');setText('#entropy',Number(s.bitplane.entropy||0).toFixed(6));setText('#energy',s.last_report?Number(s.last_report.kinetic_energy).toExponential(3):'—');setText('#words',`${s.bitplane.packed_words}/${s.bitplane.logical_words}`);setText('#mse',s.last_report?Number(s.last_report.reconstruction_mse).toExponential(3):'—');setText('#fp',s.last_report&&s.last_report.fixed_point_residual!==null?Number(s.last_report.fixed_point_residual).toExponential(3):'—');setText('#policy',`${s.policy.block_size} / ${s.policy.quantization}`);if(s.loaded){const snap=await req('/v1/os/snapshot?limit=1800');cells=snap.cells}else cells=[]}catch(e){log(e.message)}draw()}
function rot(p){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);let x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y*cp-z*sp;z=p.y*sp+z*cp;return{x,y,z}}
function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(120,170,210,.08)';for(let r=60;r<330;r+=55){ctx.beginPath();ctx.arc(w/2,h/2,r*zoom,0,Math.PI*2);ctx.stroke()}if(!cells.length){ctx.fillStyle='#71849a';ctx.font='18px system-ui';ctx.textAlign='center';ctx.fillText('Boot the demo or load a sparse field',w/2,h/2);return}let max=1;for(const p of cells)max=Math.max(max,p.x,p.y,p.z);const scale=Math.min(w,h)/(max*2.2)*zoom,center=max/2;const pts=cells.map(p=>{const q=rot({x:p.x-center,y:p.y-center,z:p.z-center});return{...p,sx:w/2+q.x*scale,sy:h/2+q.y*scale,depth:q.z}}).sort((a,b)=>b.depth-a.depth);for(const p of pts){const mag=Math.min(1,Math.abs(p.value));ctx.fillStyle=mag>.75?'#ffd36d':'#76d9ff';ctx.globalAlpha=.35+.65*mag;ctx.beginPath();ctx.arc(p.sx,p.sy,2.4+mag*3.2,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
async function action(fn,label){try{await fn();log(label);stage=(stage+1)%10;document.querySelectorAll('.stage i').forEach((e,i)=>e.classList.toggle('on',i===stage));await refresh()}catch(e){log(`${label}: ${e.message}`)}}
$('#demo').onclick=()=>action(async()=>{await req('/v1/os/boot',{method:'POST'});await req('/v1/os/demo',{method:'POST'})},'demo loaded');$('#step').onclick=()=>action(()=>req('/v1/os/step',{method:'POST'}),'single cycle');$('#run').onclick=()=>action(()=>req('/v1/os/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cycles:8})}),'run ×8');$('#auto').onclick=()=>action(()=>req('/v1/os/autorun/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({interval_seconds:.35})}),'autorun started');$('#stop').onclick=()=>action(()=>req('/v1/os/autorun/stop',{method:'POST'}),'autorun stopped');$('#shutdown').onclick=()=>action(()=>req('/v1/os/shutdown',{method:'POST'}),'kernel shutdown');
canvas.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-lx)*.006;pitch=Math.max(-1.3,Math.min(1.3,pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;draw()});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.45,Math.min(2.2,zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});setInterval(refresh,1000);refresh()})();
</script></body></html>"""
