#!/usr/bin/env python3
"""Generate end-to-end multimodal Python applications for Jarvis-X.

The factory is stdlib-only. Generated applications expose a FastAPI service and
browser UI for text, image, audio, video, generic-file, and NumPy 3D-volume
workflows, plus an optional PyTorch Conv3D autoencoder.

Lifecycle:
    specification -> source -> validate -> test -> package -> run
"""
from __future__ import annotations

import argparse
import json
import py_compile
import re
import textwrap
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass
class AppSpec:
    name: str
    package: str
    title: str
    version: str = "0.1.0"
    description: str = "Jarvis-X generated multimodal multimedia application"

    @classmethod
    def from_name(cls, name: str) -> "AppSpec":
        clean = re.sub(r"[^A-Za-z0-9_]+", "_", name.strip()).strip("_") or "jarvisx_multimodal_app"
        if clean[0].isdigit():
            clean = "app_" + clean
        return cls(clean, clean.lower(), clean.replace("_", " ").title())


TEMPLATES = {
    "requirements.txt": """
fastapi>=0.115
uvicorn[standard]>=0.30
python-multipart>=0.0.9
numpy>=1.26
pillow>=10.0
pytest>=8.0
httpx>=0.27
""",
    "requirements-ai.txt": """
torch>=2.2
opencv-python>=4.10
""",
    "Dockerfile": """
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "manage.py", "run", "--host", "0.0.0.0", "--port", "8000"]
""",
    "README.md": """
# __TITLE__

Generated by the Jarvis-X Moagi Multimodal Application Factory.

Capabilities: text, images, WAV audio, FFprobe-assisted video, arbitrary files,
NumPy 3D volumes, a browser workbench, REST API, tests, Docker packaging, and
an optional PyTorch 3D autoencoder.

Run:

    python manage.py install
    python manage.py test
    python manage.py run

Open http://127.0.0.1:8000.
""",
    "manage.py": r'''
#!/usr/bin/env python3
from __future__ import annotations
import argparse, subprocess, sys, zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PACKAGE = "__PKG__"
VERSION = "__VERSION__"

def run(cmd):
    print("+", " ".join(map(str, cmd)))
    subprocess.run(cmd, cwd=ROOT, check=True)

def package_release():
    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)
    out = dist / f"{PACKAGE}-{VERSION}.zip"
    excluded = {"__pycache__", ".pytest_cache", "dist", ".git", ".venv", "venv"}
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in ROOT.rglob("*"):
            if path.is_dir():
                continue
            rel = path.relative_to(ROOT)
            if any(part in excluded for part in rel.parts):
                continue
            zf.write(path, rel)
    print("release:", out)

def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("install"); p.add_argument("--ai", action="store_true")
    sub.add_parser("test")
    sub.add_parser("package")
    p = sub.add_parser("run")
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=8000)
    p.add_argument("--reload", action="store_true")
    args = ap.parse_args()

    if args.cmd == "install":
        run([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        if args.ai:
            run([sys.executable, "-m", "pip", "install", "-r", "requirements-ai.txt"])
    elif args.cmd == "test":
        # Keep generated-project tests independent of parent pytest addopts.
        run([sys.executable, "-m", "pytest", "-q", "-o", "addopts=", "tests"])
    elif args.cmd == "package":
        package_release()
    elif args.cmd == "run":
        cmd = [sys.executable, "-m", "uvicorn", f"{PACKAGE}.app:app",
               "--host", args.host, "--port", str(args.port)]
        if args.reload:
            cmd.append("--reload")
        run(cmd)

if __name__ == "__main__":
    main()
''',
    "__PKG__/__init__.py": '__version__ = "__VERSION__"\n',
    "__PKG__/autoencoder3d.py": r'''
from __future__ import annotations
try:
    import torch
    import torch.nn as nn
except ImportError as exc:
    raise RuntimeError("Install optional AI dependencies: python manage.py install --ai") from exc

class AutoEncoder3D(nn.Module):
    def __init__(self, channels=1, base=16, latent=32):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Conv3d(channels, base, 4, 2, 1), nn.GELU(),
            nn.Conv3d(base, base * 2, 4, 2, 1), nn.GELU(),
            nn.Conv3d(base * 2, latent, 4, 2, 1), nn.GELU())
        self.decoder = nn.Sequential(
            nn.ConvTranspose3d(latent, base * 2, 4, 2, 1), nn.GELU(),
            nn.ConvTranspose3d(base * 2, base, 4, 2, 1), nn.GELU(),
            nn.ConvTranspose3d(base, channels, 4, 2, 1), nn.Sigmoid())

    def encode(self, x):
        return self.encoder(x)

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        z = self.encode(x)
        return self.decode(z), z

    @torch.no_grad()
    def refine(self, z, steps=2, alpha=0.35):
        for _ in range(max(0, steps)):
            z = (1.0 - alpha) * z + alpha * self.encode(self.decode(z))
        return z
''',
    "__PKG__/app.py": r'''
from __future__ import annotations

import hashlib
import json
import mimetypes
import shutil
import subprocess
import tempfile
import wave
from collections import Counter
from io import BytesIO
from pathlib import Path
from typing import Literal

import numpy as np
from fastapi import FastAPI, File, HTTPException, Query, UploadFile
from fastapi.responses import HTMLResponse, Response
from PIL import Image, ImageOps
from pydantic import BaseModel, Field

from . import __version__

ROOT = Path(__file__).resolve().parent
app = FastAPI(title="__TITLE__", version=__version__, description="__DESCRIPTION__")

class TextRequest(BaseModel):
    text: str = Field(min_length=1, max_length=2_000_000)

def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def text_stats(text: str):
    words = text.split()
    freq = Counter(w.strip(".,!?;:'\"()[]{}").lower() for w in words)
    freq.pop("", None)
    return {"modality":"text", "characters":len(text), "words":len(words),
            "unique_words":len(freq), "top_words":freq.most_common(12), "preview":text[:500]}

@app.get("/", response_class=HTMLResponse)
async def home():
    return HTMLResponse("""<!doctype html><html><body style="font-family:system-ui;background:#0b1020;color:#eef;padding:2rem">
<h1>__TITLE__</h1><p>Multimodal API is operational.</p>
<ul><li>POST /api/text</li><li>POST /api/image</li><li>POST /api/audio</li>
<li>POST /api/video</li><li>POST /api/file</li><li>POST /api/volume</li></ul>
<p><a style="color:#8cf" href="/docs">OpenAPI console</a></p></body></html>""")

@app.get("/health")
async def health():
    return {"status":"ok", "service":"__PKG__", "version":__version__}

@app.post("/api/text")
async def text(req: TextRequest):
    return text_stats(req.text)

@app.post("/api/file")
async def file(file: UploadFile = File(...)):
    data = await file.read()
    guessed, _ = mimetypes.guess_type(file.filename or "upload.bin")
    return {"modality":"file", "filename":file.filename, "content_type":file.content_type or guessed,
            "bytes":len(data), "sha256":digest(data)}

@app.post("/api/image")
async def image(file: UploadFile = File(...),
                transform: Literal["none","grayscale","thumbnail","mirror","autocontrast"] = Query("none"),
                return_image: bool = Query(False)):
    data = await file.read()
    try:
        with Image.open(BytesIO(data)) as im:
            original = im.size
            if transform == "grayscale":
                out = ImageOps.grayscale(im)
            elif transform == "thumbnail":
                out = im.copy(); out.thumbnail((768, 768))
            elif transform == "mirror":
                out = ImageOps.mirror(im)
            elif transform == "autocontrast":
                out = ImageOps.autocontrast(im.convert("RGB"))
            else:
                out = im.copy()
            arr = np.asarray(out.convert("RGB"), dtype=np.float32)
            mean = [round(float(v), 3) for v in arr.mean(axis=(0,1))]
            buf = BytesIO(); out.convert("RGB").save(buf, format="PNG"); encoded = buf.getvalue()
    except Exception as exc:
        raise HTTPException(400, f"image decode failed: {exc}") from exc
    if return_image:
        return Response(encoded, media_type="image/png")
    return {"modality":"image", "original_size":list(original), "output_size":list(out.size),
            "transform":transform, "mean_rgb":mean, "sha256":digest(data)}

@app.post("/api/audio")
async def audio(file: UploadFile = File(...)):
    data = await file.read()
    result = {"modality":"audio", "filename":file.filename, "bytes":len(data), "sha256":digest(data)}
    try:
        with wave.open(BytesIO(data), "rb") as wav:
            frames, rate = wav.getnframes(), wav.getframerate()
            result.update(format="wav", channels=wav.getnchannels(), sample_rate_hz=rate,
                          frames=frames, duration_seconds=round(frames/rate if rate else 0.0, 6))
    except Exception:
        result["format"] = "unknown-or-compressed"
    return result

@app.post("/api/video")
async def video(file: UploadFile = File(...)):
    data = await file.read()
    result = {"modality":"video", "filename":file.filename, "bytes":len(data), "sha256":digest(data)}
    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        result["probe"] = "ffprobe-unavailable"
        return result
    with tempfile.TemporaryDirectory() as td:
        path = Path(td) / ("input" + (Path(file.filename or "").suffix or ".bin"))
        path.write_bytes(data)
        proc = subprocess.run([ffprobe, "-v", "quiet", "-print_format", "json",
                               "-show_format", "-show_streams", str(path)],
                              capture_output=True, text=True)
    if proc.returncode:
        result["probe"] = "unreadable"
        return result
    try:
        probe = json.loads(proc.stdout)
    except json.JSONDecodeError:
        result["probe"] = "invalid-json"
        return result
    result["streams"] = probe.get("streams", [])
    result["format"] = probe.get("format", {})
    return result

@app.post("/api/volume")
async def volume(file: UploadFile = File(...)):
    data = await file.read()
    try:
        arr = np.load(BytesIO(data), allow_pickle=False)
        if arr.ndim not in (3,4,5) or not np.issubdtype(arr.dtype, np.number):
            raise ValueError("expected numeric 3D/4D/5D NumPy array")
        x = np.asarray(arr, dtype=np.float32)
        x = np.where(np.isfinite(x), x, 0.0)
    except Exception as exc:
        raise HTTPException(400, f"3D volume decode failed: {exc}") from exc
    nz = int(np.count_nonzero(x))
    return {"modality":"volume3d", "shape":list(x.shape), "elements":int(x.size),
            "min":float(x.min()) if x.size else 0.0, "max":float(x.max()) if x.size else 0.0,
            "mean":float(x.mean()) if x.size else 0.0,
            "sparsity":float(1.0 - nz/max(x.size,1)), "sha256":digest(data)}
''',
    "tests/test_smoke.py": r'''
import io
import numpy as np
from fastapi.testclient import TestClient
from __PKG__.app import app

client = TestClient(app)

def test_health():
    assert client.get("/health").json()["status"] == "ok"

def test_text():
    r = client.post("/api/text", json={"text":"one two two"})
    assert r.status_code == 200 and r.json()["words"] == 3

def test_volume():
    arr = np.zeros((8,8,8), dtype=np.float32)
    arr[2:6,2:6,2:6] = 1
    buf = io.BytesIO(); np.save(buf, arr)
    r = client.post("/api/volume", files={"file":("volume.npy", buf.getvalue(), "application/octet-stream")})
    assert r.status_code == 200 and r.json()["shape"] == [8,8,8]
''',
}


def render(text: str, spec: AppSpec) -> str:
    mapping = {
        "__PKG__": spec.package,
        "__TITLE__": spec.title,
        "__VERSION__": spec.version,
        "__DESCRIPTION__": spec.description,
        "__DIST__": spec.package.replace("_", "-"),
    }
    for key, value in mapping.items():
        text = text.replace(key, value)
    return textwrap.dedent(text).lstrip("\n")


def write_project(root: Path, spec: AppSpec, force: bool = False) -> None:
    if root.exists() and any(root.iterdir()) and not force:
        raise SystemExit(f"destination is not empty: {root}; use --force to overwrite generated files")
    root.mkdir(parents=True, exist_ok=True)
    for rel, body in TEMPLATES.items():
        path = root / render(rel, spec)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(body, spec), encoding="utf-8")
    for folder in ("uploads", "outputs", "checkpoints"):
        (root / folder).mkdir(exist_ok=True)
    (root / "app_spec.json").write_text(json.dumps(asdict(spec), indent=2), encoding="utf-8")


def validate_python(root: Path) -> None:
    failures = []
    for path in root.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        try:
            py_compile.compile(str(path), doraise=True)
        except Exception as exc:
            failures.append((path, exc))
    if failures:
        for path, exc in failures:
            print("FAIL", path, exc)
        raise SystemExit(2)


def release_zip(root: Path, spec: AppSpec) -> Path:
    dist = root / "dist"
    dist.mkdir(exist_ok=True)
    out = dist / f"{spec.package}-{spec.version}.zip"
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in root.rglob("*"):
            if path.is_dir() or "dist" in path.relative_to(root).parts or "__pycache__" in path.parts:
                continue
            zf.write(path, path.relative_to(root))
    return out


def add_create_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("name")
    p.add_argument("--output")
    p.add_argument("--title")
    p.add_argument("--version", default="0.1.0")
    p.add_argument("--description", default="Jarvis-X generated multimodal multimedia application")
    p.add_argument("--force", action="store_true")


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate end-to-end multimodal/multimedia Python applications")
    sub = ap.add_subparsers(dest="command", required=True)
    p = sub.add_parser("create"); add_create_args(p)
    p = sub.add_parser("all"); add_create_args(p)
    p = sub.add_parser("validate"); p.add_argument("project")
    p = sub.add_parser("package"); p.add_argument("project")
    args = ap.parse_args()

    if args.command in {"create", "all"}:
        spec = AppSpec.from_name(args.name)
        if args.title:
            spec.title = args.title
        spec.version = args.version
        spec.description = args.description
        root = Path(args.output or spec.name).resolve()
        write_project(root, spec, args.force)
        validate_python(root)
        if args.command == "all":
            print("release:", release_zip(root, spec))
        print("generated:", root)
        return

    root = Path(args.project).resolve()
    validate_python(root)
    if args.command == "package":
        spec_path = root / "app_spec.json"
        if not spec_path.exists():
            raise SystemExit("app_spec.json not found")
        print("release:", release_zip(root, AppSpec(**json.loads(spec_path.read_text(encoding="utf-8")))))


if __name__ == "__main__":
    main()
